Asvf 111
Actualize-Apprenticeship-Team-Gator/bigographer pull request #2
Opened 2018-02-02 02:05 UTC by MrFuentastic

2018-02-02 02:08 UTC, gatorjuice submitted a review, later dismissed

2018-02-02 02:08 UTC, gatorjuice commented on app/assets/javascripts/app.js
> +                var color = this.favoriteColors.pop();
var is old syntax, we can use a 'let' here

2018-02-02 02:08 UTC, gatorjuice commented on app/assets/stylesheets/graphs.scss
> +
extra lines

2018-02-02 02:08 UTC, gatorjuice commented on public/custom.css
> +
extra line

2018-02-02 02:08 UTC, gatorjuice commented on test/controllers/api/v1/codes_controller_test.rb
> +    assert_equal data, {"results"=>[[{"x"=>100, "y"=>201}, {"x"=>500, "y"=>1001}, {"x"=>1000, "y"=>2001}, {"x"=>1500, "y"=>3001}, {"x"=>2000, "y"=>4001}, {"x"=>2500, "y"=>5001}, {"x"=>3000, "y"=>6001
lets break this out so its not all one one line

2018-02-06 02:09 UTC, walshification requested changes
Let's add some test cases for processes more than one submitted code block.

2018-02-09 01:42 UTC, walshification approved these changes

2018-02-09 01:43 UTC, merged